/* ============================================================================
   知识图谱节点 → 站内教材落点 的映射表
   ----------------------------------------------------------------------------
   自动生成，不要手改。生成规则（每一级都要站得住的证据）：
     ① 图谱自己的叶子节点用 TB_LINKS（在本表之外，mindmap 直接查）
     ② 全站名称表 SITE_LINKS / CONCEPT_LINKS 已覆盖的，不在本表里
     ③ 某篇教材的「小节标题」就是这个节点名 → 落到那一节
     ④ 节点名（或它 ≥3 字的子串，如"静力学平衡方程"→"平衡方程"）出现在
        它自己所属那一篇的正文里 → 落到那一篇
     ⑤ 只在别的篇出现、且出现 ≥5 次、本篇一次都没有 → 才敢换篇
     ⑥ 以上都不满足 → 不写进本表，由 mindmap 兜底成 ai_qa.html?q=节点名
   每条都带 ev（证据）；生成时自检过：教材落点一定真的含该依据词。
   来源：textbooks/{statics,kinematics,dynamics,analytical} 的锚点标题与正文。
   ============================================================================ */
window.KP_LINKS = {
  "变分法": { url: "textbooks/analytical/index.html?target=hamilton-3", ev: "本篇正文含\"变分法\"×1" },
  "变质量系统": { url: "textbooks/dynamics/index.html?target=dyn2-3", ev: "小节标题『变质量系统』同名" },
  "初始条件": { url: "textbooks/dynamics/index.html?target=dyn1-3", ev: "本篇正文含\"初始条件\"×4" },
  "纯滚动": { url: "textbooks/kinematics/index.html?target=p4m3", ev: "本篇正文含\"纯滚动\"×2" },
  "达朗贝尔-拉格朗日原理": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"达朗贝尔\"×9" },
  "导杆机构": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"杆机构\"×4" },
  "第二类拉格朗日方程": { url: "textbooks/analytical/index.html?target=lagrange-second-kind", ev: "小节标题『第二类拉格朗日方程』同名" },
  "点的加速度": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"的加速度\"×4" },
  "点的速度": { url: "textbooks/kinematics/index.html?target=p2m1", ev: "本篇正文含\"点的速度\"×2" },
  "定理的选择策略": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"定理的\"×2" },
  "定轴转动刚体的加速度": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"定轴转动\"×17" },
  "动静法解题步骤": { url: "textbooks/analytical/index.html", ev: "本篇无；analytical正文含\"动静法\"×8" },
  "动力学建模": { url: "textbooks/dynamics/index.html?target=dyn1-2", ev: "本篇正文含\"动力学建模\"×1" },
  "动力学普遍定理": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"普遍定理\"×2" },
  "动量矩": { url: "textbooks/dynamics/index.html?target=dyn3", ev: "本篇正文含\"动量矩\"×8" },
  "动量矩守恒": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"动量矩\"×8" },
  "动量守恒": { url: "textbooks/dynamics/index.html?target=dyn2-1", ev: "本篇正文含\"动量守恒\"×2" },
  "动摩擦": { url: "textbooks/statics/textbook.html?target=m77", ev: "小节标题『滑动摩擦的概念与物理成因』含该词" },
  "动平衡": { url: "textbooks/dynamics/index.html", ev: "人工：属动力学，静力学那 7 次在扩展章节" },
  "动系转动": { url: "textbooks/kinematics/index.html?target=p3m3", ev: "本篇正文含\"动系转动\"×6" },
  "对称性与守恒律": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"对称性\"×5" },
  "多自由度振动": { url: "textbooks/analytical/index.html?target=two-dof-vibration", ev: "本篇正文含\"多自由度振动\"×3" },
  "二、动量定理": { url: "textbooks/dynamics/index.html?target=dyn2", ev: "本篇正文含\"二动量定理\"×2" },
  "二、刚体的基本运动": { url: "textbooks/kinematics/index.html?target=part2", ev: "本篇正文含\"二刚体的基本运动\"×2" },
  "二、虚位移原理": { url: "textbooks/analytical/index.html?target=virtual-work", ev: "本篇正文含\"二虚位移原理\"×1" },
  "二力杆": { url: "textbooks/statics/textbook.html?target=page12", ev: "本篇正文含\"二力杆\"×12" },
  "分析力学基础": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"分析力学\"×11" },
  "幅频特性": { url: "textbooks/analytical/index.html?target=sdof-forced", ev: "本篇正文含\"幅频特性\"×1" },
  "刚体定轴转动微分方程": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"动微分方程\"×7" },
  "刚体惯性力系简化": { url: "textbooks/analytical/index.html?target=rigid-inertia-system", ev: "小节标题『刚体惯性力系简化』同名" },
  "刚体上各点速度": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"各点速度\"×3" },
  "刚体微幅振荡": { url: "textbooks/analytical/index.html?target=rigid-small-oscillation", ev: "小节标题『刚体微幅振荡』同名" },
  "隔振": { url: "textbooks/analytical/index.html?target=sdof-forced", ev: "本篇正文含\"隔振\"×1" },
  "共振": { url: "textbooks/analytical/index.html?target=sdof-forced", ev: "本篇正文含\"共振\"×8" },
  "固定端约束": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"固定端\"×8" },
  "固有频率": { url: "textbooks/analytical/index.html?target=two-dof-vibration", ev: "本篇正文含\"固有频率\"×17" },
  "惯性主轴": { url: "textbooks/analytical/index.html", ev: "本篇无；analytical正文含\"惯性主\"×8" },
  "光滑面约束": { url: "textbooks/statics/textbook.html?target=m50", ev: "本篇正文含\"光滑面约束\"×1" },
  "广义力": { url: "textbooks/analytical/index.html?target=generalized-force", ev: "小节标题『广义力』同名" },
  "广义坐标": { url: "textbooks/analytical/index.html?target=lagrange", ev: "本篇正文含\"广义坐标\"×35" },
  "轨迹": { url: "textbooks/kinematics/index.html?target=part1", ev: "本篇正文含\"轨迹\"×21" },
  "哈密顿-雅可比方程": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"哈密顿\"×18" },
  "哈密顿函数": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"哈密顿\"×18" },
  "哈密顿原理": { url: "textbooks/analytical/index.html?target=hamilton-1", ev: "小节标题『作用量与哈密顿原理』含该词" },
  "合力与分力": { url: "textbooks/statics/textbook.html?target=m34", ev: "本篇正文含\"合力与分力\"×1" },
  "恢复系数": { url: "textbooks/analytical/index.html?target=collision", ev: "本篇无；analytical正文含\"恢复系数\"×20" },
  "火箭运动方程": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"运动方程\"×1" },
  "基本概念与模型": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"基本概念\"×2" },
  "加速度合成": { url: "textbooks/kinematics/index.html?target=p3m3", ev: "小节标题『加速度合成』同名" },
  "加速度矢量三角形": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"速度矢量三角形\"×1" },
  "减振": { url: "textbooks/analytical/index.html?target=sdof-forced", ev: "本篇正文含\"减振\"×2" },
  "剪力": { url: "textbooks/statics/textbook.html?target=m14", ev: "本篇正文含\"剪力\"×3" },
  "剪切": { url: "textbooks/statics/textbook.html?target=m2", ev: "本篇正文含\"剪切\"×1" },
  "简化中心": { url: "textbooks/statics/textbook.html?target=m52", ev: "本篇正文含\"简化中心\"×3" },
  "简谐振动": { url: "textbooks/analytical/index.html?target=rigid-small-oscillation", ev: "本篇正文含\"简谐振动\"×3" },
  "角动量守恒": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"动量守恒\"×2" },
  "铰链约束": { url: "textbooks/statics/textbook.html?target=m5", ev: "本篇正文含\"铰链约束\"×1" },
  "截面法": { url: "textbooks/statics/textbook.html?target=m68", ev: "小节标题『截面法：快速求指定杆件内力』含该词" },
  "解题技巧": { url: "textbooks/analytical/index.html", ev: "人工：非知识点，归本篇" },
  "静力学基础": { url: "textbooks/statics/textbook.html?target=page8", ev: "本篇正文含\"静力学基础\"×2" },
  "静力学平衡方程": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"静力学平衡\"×1" },
  "静摩擦": { url: "textbooks/statics/textbook.html?target=m78", ev: "小节标题『静摩擦力最大静摩擦力与滑动趋势』含该词" },
  "绝对加速度": { url: "textbooks/kinematics/index.html?target=p3m3", ev: "本篇正文含\"绝对加速度\"×1" },
  "绝对速度": { url: "textbooks/kinematics/index.html?target=p3m2", ev: "本篇正文含\"绝对速度\"×3" },
  "绝对运动": { url: "textbooks/kinematics/index.html?target=part3", ev: "本篇正文含\"绝对运动\"×3" },
  "空间汇交力系": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"汇交力系\"×7" },
  "空间力偶系": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"空间力\"×42" },
  "空间力系平衡方程": { url: "textbooks/statics/textbook.html?target=m59", ev: "小节标题『空间力系平衡方程与解题顺序』含该词" },
  "空间任意力系": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"任意力系\"×45" },
  "拉格朗日乘子法": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"拉格朗日乘子\"×1" },
  "拉格朗日函数": { url: "textbooks/analytical/index.html?target=energy-integral", ev: "本篇正文含\"拉格朗日函数\"×5" },
  "理想约束": { url: "textbooks/analytical/index.html?target=ideal-constraint", ev: "小节标题『理想约束』同名" },
  "力的基本概念": { url: "textbooks/statics/textbook.html?target=page1", ev: "本篇正文含\"力的基本概念\"×2" },
  "力的运算与简化": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"与简化\"×2" },
  "力系的平衡": { url: "textbooks/statics/textbook.html?target=m53", ev: "本篇正文含\"力系的平衡\"×1" },
  "两类问题": { url: "textbooks/dynamics/index.html?target=dyn1-3", ev: "小节标题『两类问题』同名" },
  "两自由度系统振动": { url: "textbooks/analytical/index.html?target=two-dof-vibration", ev: "小节标题『两自由度系统振动』同名" },
  "挠度": { url: "textbooks/statics/textbook.html?target=m7", ev: "本篇正文含\"挠度\"×6" },
  "能量法": { url: "textbooks/dynamics/index.html?target=dyn4-1", ev: "本篇正文含\"能量法\"×2" },
  "能量法解题步骤": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"能量法\"×2" },
  "能量积分": { url: "textbooks/analytical/index.html?target=energy-integral", ev: "小节标题『能量积分』同名" },
  "诺特定理": { url: "textbooks/analytical/index.html?target=hamilton-3", ev: "本篇正文含\"诺特定理\"×1" },
  "欧拉-拉格朗日方程": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"拉格朗日方程\"×29" },
  "耦合振动": { url: "textbooks/analytical/index.html?target=two-dof-vibration", ev: "本篇正文含\"耦合振动\"×2" },
  "碰撞冲量": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"碰撞冲\"×1" },
  "碰撞能量": { url: "textbooks/analytical/index.html?target=collision-energy", ev: "小节标题『碰撞能量』同名" },
  "频率": { url: "textbooks/analytical/index.html?target=two-dof-vibration", ev: "本篇正文含\"频率\"×27" },
  "平衡方程": { url: "textbooks/statics/textbook.html?target=m53", ev: "小节标题『平衡方程与取矩技巧』含该词" },
  "平衡力系": { url: "textbooks/statics/textbook.html?target=m33", ev: "小节标题『公理二：加减平衡力系公理』含该词" },
  "平面桁架基本假设": { url: "textbooks/statics/textbook.html?target=m66", ev: "小节标题『平面桁架基本假设与杆件轴力』含该词" },
  "平面汇交力系": { url: "textbooks/statics/textbook.html?target=page12", ev: "本篇正文含\"平面汇交力系\"×3" },
  "平面力偶等效定理": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"平面力\"×10" },
  "平面力偶系": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"平面力\"×10" },
  "平面力系平衡方程": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"力系平衡方程\"×2" },
  "平面运动方程": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"平面运动\"×21" },
  "平面运动分解为平动与转动": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"平面运动分解为\"×1" },
  "平面运动角加速度": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"平面运动\"×21" },
  "平面运动角速度": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"平面运动\"×21" },
  "平面运动微分方程": { url: "textbooks/dynamics/index.html?target=dyn3-3", ev: "小节标题『平面运动微分方程』同名" },
  "平行力系": { url: "textbooks/statics/textbook.html?target=page9", ev: "本篇正文含\"平行力系\"×5" },
  "平行力系中心": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"平行力系\"×5" },
  "平行轴定理": { url: "textbooks/dynamics/index.html?target=dyn3-1", ev: "本篇正文含\"平行轴定理\"×1" },
  "牵连加速度": { url: "textbooks/kinematics/index.html?target=p3m3", ev: "本篇正文含\"牵连加速度\"×2" },
  "牵连速度": { url: "textbooks/kinematics/index.html?target=p3m2", ev: "本篇正文含\"牵连速度\"×3" },
  "牵连运动": { url: "textbooks/kinematics/index.html?target=part3", ev: "本篇正文含\"牵连运动\"×2" },
  "曲柄连杆机构": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"连杆机构\"×3" },
  "曲率半径": { url: "textbooks/kinematics/index.html?target=p1m3", ev: "本篇正文含\"曲率半径\"×4" },
  "取矩技巧": { url: "textbooks/statics/textbook.html?target=m53", ev: "小节标题『平衡方程与取矩技巧』含该词" },
  "柔索约束": { url: "textbooks/statics/textbook.html?target=m27", ev: "本篇正文含\"柔索约束\"×1" },
  "三、点的合成运动 ★": { url: "textbooks/kinematics/index.html?target=part3", ev: "本篇正文含\"三点的合成运动★\"×2" },
  "三、动量矩定理": { url: "textbooks/dynamics/index.html?target=dyn3", ev: "本篇正文含\"三动量矩定理\"×2" },
  "三、拉格朗日方程": { url: "textbooks/analytical/index.html?target=lagrange", ev: "本篇正文含\"三拉格朗日方程\"×1" },
  "三力平衡汇交定理": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"三力平衡\"×12" },
  "守恒量": { url: "textbooks/analytical/index.html?target=energy-integral", ev: "本篇正文含\"守恒量\"×6" },
  "受力分析技巧": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"受力分析\"×5" },
  "受力图常见错误": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"常见错误\"×8" },
  "受迫振动": { url: "textbooks/analytical/index.html?target=sdof-forced", ev: "小节标题『单自由度系统受迫振动』含该词" },
  "受迫振动幅值": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"受迫振动\"×8" },
  "瞬时加速度": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"加速度\"×129" },
  "瞬时速度": { url: "textbooks/kinematics/index.html?target=p4m3", ev: "本篇正文含\"瞬时速度\"×3" },
  "四、动能定理": { url: "textbooks/dynamics/index.html?target=dyn4", ev: "本篇正文含\"四动能定理\"×2" },
  "四、刚体平面运动 ★": { url: "textbooks/kinematics/index.html?target=part4", ev: "本篇正文含\"四刚体平面运动★\"×2" },
  "四、振动": { url: "textbooks/analytical/index.html?target=vibration", ev: "本篇正文含\"四振动\"×1" },
  "速度分析技巧": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"速度分析\"×13" },
  "速度合成": { url: "textbooks/kinematics/index.html?target=p3m2", ev: "小节标题『速度合成vₐ=vₑ+vᵣ』含该词" },
  "速度矢量三角形": { url: "textbooks/kinematics/index.html?target=p3m2", ev: "本篇正文含\"速度矢量三角形\"×1" },
  "弯矩": { url: "textbooks/statics/textbook.html?target=m14", ev: "本篇正文含\"弯矩\"×3" },
  "完全弹性碰撞": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"弹性碰撞\"×1" },
  "完全非弹性碰撞": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"非弹性碰撞\"×1" },
  "完整约束与非完整约束": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"非完整约束\"×2" },
  "无阻尼自由振动": { url: "textbooks/analytical/index.html?target=multi-dof-vibration", ev: "本篇正文含\"无阻尼自由振动\"×1" },
  "五、碰撞": { url: "textbooks/analytical/index.html?target=collision", ev: "本篇正文含\"五碰撞\"×1" },
  "物理摆": { url: "textbooks/analytical/index.html?target=rigid-small-oscillation", ev: "本篇正文含\"物理摆\"×1" },
  "相对加速度": { url: "textbooks/kinematics/index.html?target=p3m3", ev: "本篇正文含\"相对加速度\"×2" },
  "相对速度": { url: "textbooks/kinematics/index.html?target=p3m2", ev: "本篇正文含\"相对速度\"×9" },
  "相对运动": { url: "textbooks/kinematics/index.html?target=part3", ev: "本篇正文含\"相对运动\"×6" },
  "相空间": { url: "textbooks/analytical/index.html?target=hamilton-3", ev: "本篇正文含\"相空间\"×1" },
  "相频特性": { url: "textbooks/analytical/index.html", ev: "本篇正文含\"频特性\"×1" },
  "相位": { url: "textbooks/analytical/index.html?target=sdof-free", ev: "本篇正文含\"相位\"×3" },
  "小角度近似": { url: "textbooks/analytical/index.html?target=rigid-small-oscillation", ev: "本篇正文含\"小角度近似\"×1" },
  "形心": { url: "textbooks/statics/textbook.html?target=m54", ev: "本篇正文含\"形心\"×9" },
  "虚功": { url: "textbooks/analytical/index.html?target=virtual-work", ev: "本篇正文含\"虚功\"×33" },
  "虚位移": { url: "textbooks/analytical/index.html?target=virtual-displacement-work", ev: "小节标题『虚位移虚功』含该词" },
  "旋转矢量法": { url: "textbooks/analytical/index.html", ev: "人工：属振动，被\"矢量法\"误带到运动学" },
  "循环积分": { url: "textbooks/analytical/index.html?target=cyclic-integral", ev: "小节标题『循环积分』同名" },
  "循环坐标": { url: "textbooks/analytical/index.html?target=cyclic-integral", ev: "本篇正文含\"循环坐标\"×4" },
  "一、达朗贝尔原理": { url: "textbooks/analytical/index.html?target=dalambert", ev: "本篇正文含\"一达朗贝尔原理\"×1" },
  "一、点的运动学": { url: "textbooks/kinematics/index.html?target=part1", ev: "本篇正文含\"一点的运动学\"×2" },
  "一、质点动力学": { url: "textbooks/dynamics/index.html?target=dyn1", ev: "本篇正文含\"一质点动力学\"×2" },
  "应变": { url: "textbooks/statics/textbook.html?target=m7", ev: "本篇正文含\"应变\"×2" },
  "应力": { url: "textbooks/statics/textbook.html?target=m7", ev: "本篇正文含\"应力\"×17" },
  "应力与应变": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"应力与\"×3" },
  "约束反力": { url: "textbooks/statics/textbook.html?target=m27", ev: "小节标题『约束与约束反力』含该词" },
  "约束分类": { url: "textbooks/analytical/index.html?target=constraints", ev: "小节标题『约束分类』同名" },
  "约束力": { url: "textbooks/analytical/index.html?target=virtual-work", ev: "本篇正文含\"约束力\"×6" },
  "约束与受力分析": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"约束与受力\"×3" },
  "运动方程": { url: "textbooks/kinematics/index.html", ev: "人工：本篇核心内容，教材用词不同" },
  "运动分解": { url: "textbooks/kinematics/index.html?target=p4m1", ev: "本篇正文含\"运动分解\"×2" },
  "运动学分析步骤": { url: "textbooks/kinematics/index.html", ev: "本篇正文含\"运动学\"×18" },
  "振幅": { url: "textbooks/analytical/index.html?target=sdof-free", ev: "本篇正文含\"振幅\"×3" },
  "正则方程": { url: "textbooks/analytical/index.html?target=hamilton-3", ev: "本篇正文含\"正则方程\"×1" },
  "质点动力学": { url: "textbooks/dynamics/index.html?target=dyn1", ev: "本篇正文含\"质点动力学\"×2" },
  "质点系动力学": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"质点系\"×1" },
  "质点运动微分方程": { url: "textbooks/dynamics/index.html", ev: "本篇正文含\"运动微分方程\"×7" },
  "重心": { url: "textbooks/statics/textbook.html?target=m2", ev: "本篇正文含\"重心\"×1" },
  "周期": { url: "textbooks/analytical/index.html?target=sdof-free", ev: "本篇正文含\"周期\"×5" },
  "轴力": { url: "textbooks/statics/textbook.html?target=page12", ev: "本篇正文含\"轴力\"×18" },
  "主振型": { url: "textbooks/analytical/index.html?target=two-dof-vibration", ev: "本篇正文含\"主振型\"×7" },
  "自由度": { url: "textbooks/analytical/index.html?target=sdof-free", ev: "小节标题『单自由度系统自由振动』含该词" },
  "阻尼比": { url: "textbooks/analytical/index.html?target=sdof-forced", ev: "本篇正文含\"阻尼比\"×1" },
  "组合截面的形心": { url: "textbooks/statics/textbook.html", ev: "本篇正文含\"截面的\"×2" },
  "最小作用量原理": { url: "textbooks/analytical/index.html?target=hamilton-1", ev: "本篇正文含\"最小作用量原理\"×1" },
};
